[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"
# [build]
# target = "armv7-unknown-linux-gnueabihf"
# 
# [target.armv7-unknown-linux-gnueabihf]
# linker = "arm-none-linux-gnueabihf-gcc"

# [target.armv7-unknown-linux-gnueabihf]
# linker = "arm-none-linux-gnueabihf-gcc"
# rustflags = ["-C", "linker=arm-none-linux-gnueabihf-gcc"]
